// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	config "github.com/peak-ai/ais-service-discovery-go/plugins/incubator/local-plane/config"
	mock "github.com/stretchr/testify/mock"

	types "github.com/peak-ai/ais-service-discovery-go/pkg/types"
)

// Resolver is an autogenerated mock type for the Resolver type
type Resolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: resolver
func (_m *Resolver) Resolve(resolver config.Resolver) (*types.Response, error) {
	ret := _m.Called(resolver)

	var r0 *types.Response
	if rf, ok := ret.Get(0).(func(config.Resolver) *types.Response); ok {
		r0 = rf(resolver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(config.Resolver) error); ok {
		r1 = rf(resolver)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
